# Copyright 2026 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add github_organization tables

Revision ID: 5bbe8d06028c
Revises: afd1423112ed
Create Date: 2026-07-14 07:27:31.103565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "5bbe8d06028c"
down_revision: Union[str, Sequence[str], None] = "afd1423112ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=False),
        sa.Column(
            "login", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_github_organization_github_id"),
        "github_organization",
        ["github_id"],
        unique=True,
    )
    op.create_table(
        "github_organization_membership",
        sa.Column("user_github_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["github_organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_github_id"],
            ["user_github.id"],
        ),
        sa.PrimaryKeyConstraint("user_github_id", "organization_id"),
    )
    op.create_index(
        op.f("ix_github_organization_membership_organization_id"),
        "github_organization_membership",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_github_organization_membership_organization_id"),
        table_name="github_organization_membership",
    )
    op.drop_table("github_organization_membership")
    op.drop_index(
        op.f("ix_github_organization_github_id"), table_name="github_organization"
    )
    op.drop_table("github_organization")
    # ### end Alembic commands ###
