[project]
name = "openarm-online-web"
version = "0.0.1"
description = "The web part of OpenArm Online"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "boto3>=1.43.17",
    "fastapi-pagination>=0.15.10",
    "fastapi[standard]>=0.128.8",
    "jinja2>=3.1.6",
    "psycopg[binary]>=3.3.2",
    "pyjwt>=2.11.0",
    "sqlmodel>=0.0.33",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "requests>=2.34.2",
]
